version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'vendure'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'vendure'
      # You can use whatever password you like
      MYSQL_PASSWORD: '#AceElectronicos'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '#AceElectronicos'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - "./my-db:/var/lib/mysql"

  node:
    image: "node:12"
    user: "node"
    working_dir: /home/node/app/
    depends_on: 
      - db
    environment:
      - NODE_ENV=production
    volumes:
      - "./aceserver:/home/node/app"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '4000:3000'
    expose:
      - "4000"
    command: bash -c "npm install && yarn start"
# Names our volume
volumes:
  my-db:
